name: hama
description: A Flutter project for booking rooms with Firebase Auth and Firestore.
publish_to: 'none' # Prevent accidental publishing

version: 1.0.0+1

environment:
  sdk: '>=3.7.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Icons
  cupertino_icons: ^1.0.8

  # Firebase packages
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.17.5

  # State Management & Util
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Assets (opsional, bisa tambahkan gambar/icon di sini)
  # assets:
  #   - assets/images/
